---
azs:
- name: default
vm_types:
- name: default
  cloud_properties:
    ephemeral_disk:
      size: 1024
      type: gp2
compilation:
  workers: 2
  network: default
  az: default
  reuse_compilation_vm: true
  vm_type: default
networks:
- name: default
  subnets:
  - az: default
    reserved: [10.244.3.1]
    range: 10.244.3.0/24
    cloud_properties:
      name: default
